### ISSUE TITLE
Calling POST: /api/users gives HTTP response code 500.

### ISSUE THREAD

**Issue by robsaa** [wilsonwu/netcoreauth#1]
Hi,

I am getting HTTP response code 500 when trying to post or to api/Users, 
also when i am trying to call GET api/Users/checkemail/{email}.

Also when navigating to http://localhost:4999/api/Users i get HTTP response 404 not found.

Can you help me?

**Comment by wilsonwu** [comment]
Does the database and database connection setup correct?

**Comment by robsaa** [comment]
Yes, i believe so. I have tried using both Windows Authentication and SQL server authentication.

"SQLSERVERDB": "server=tcp:Robin-PC\\SQLEXPRESS01.database.windows.net,1433;Initial Catalog=Test;Persist Security Info=False;User ID=sa;Password=12345;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

I can connect to the SQL server from SSMS.

**Comment by wilsonwu** [comment]
A little hard to identify your problem, you can try to switch to debug mode in VS and try to find which code make this happen.

**Comment by robsaa** [comment]
But should i not be able to navigate to the http://localhost:4999/api/Users in the browser? 
It gives me 404 not found. 

I will check further, thank you.

**Comment by wilsonwu** [comment]
You can create a user in database user table, and try to use postman to try to call the email address checking API, this API is the simplest one, if it can't work that means you have a problem with you .NET environment.

**Comment by robsaa** [comment]
I checked in both swagger and postman. Both returns 500 internal server error when trying to call api/users/chechemail/{email}. Must be something wrong with the .NET environment as you say.

**Comment by robsaa** [comment]
I managed to find the error:

netcoreauth.api> System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - Sertifikatkjeden ble utstedt av en instans som ikke er klarert.) ---> System.ComponentModel.Win32Exception: Sertifikatkjeden ble utstedt av en instans som ikke er klarert

Which means: The certificate chain was issued by an authority that is not trusted.

Now i need to solve the error.

**Comment by robsaa** [comment]
Solved for now by setting Encrypt=False;TrustServerCertificate=True

But the    
 "UserAuthSecretKey": "abc123!321cba" should be changed to a longer secret. 

I am getting the following error:

netcoreauth.api> System.ArgumentOutOfRangeException: IDX10603: The algorithm: 'HS256' requires the SecurityKey.KeySize to be greater than '128' bits. KeySize reported: '104'.

**Comment by wilsonwu** [comment]
Thanks, I think I need to change the sample key to a better one.
